# Created for wslx 0.1.2 submission.
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Shanewas.wslx
PackageVersion: 0.1.2
Platform:
  - Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: wslx.exe
    PortableCommandAlias: wslx
ReleaseDate: 2026-10-01
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/shanewas/wslx/releases/download/v0.1.2/wslx_0.1.2_windows_amd64.zip
    InstallerSha256: 71C7E3BBACCD0087B41CA69B64A5A231DBFC100E8189847D61C9C99E7CD6192C
  - Architecture: arm64
    InstallerUrl: https://github.com/shanewas/wslx/releases/download/v0.1.2/wslx_0.1.2_windows_arm64.zip
    InstallerSha256: 39B93463F6BA696EC53650C8D0B4A1047DE1709303218997707FB7CA3112F9E3
ManifestType: installer
ManifestVersion: 1.12.0
